spring:
  datasource:
    url: jdbc:mysql://localhost:3314/ads_db
    username: ads_user
    password: ads_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop