package com.example.Model;

public enum CategoryType {

    HOME_AND_HOUSEHOLD,
    GARDEN_AND_OUTDOOR_ENVIRONMENT,
    CHILDREN_AND_FAMILY,
    TOYS_AND_HOBBIES,
    GAMING_AND_ENTERTAINMENT,
    COMPUTER_PRODUCTS,
    MOBILE_WEARABLES,
    SOUND_AND_IMAGE,
    PHOTO_AND_VIDEO,
    CLOTHING_ACCESSORIES,
    BEAUTY_AND_HEALTH,
    SPORTS_AND_LEISURE,
    RENOVATION_AND_CONSTRUCTION,
    VEHICLES_ACCESSORIES,
    PERSONAL_FINANS,
    TRAVELS
}


